/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista1;

import java.util.LinkedList;
import modelos.Comida;

/**
 *
 * @author munoz
 */
public class VtnConsultarComida extends javax.swing.JInternalFrame {

    /**
     * Creates new form VtnConsultarComida
     */
    public VtnConsultarComida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanelInferior = new javax.swing.JPanel();
        jPanelSuperior = new javax.swing.JPanel();
        jLabelTituloJFrame = new javax.swing.JLabel();
        jLabelIconoOrganizacion = new javax.swing.JLabel();
        jPanelCentral = new javax.swing.JPanel();
        jPanelComidaNoEncontrada = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelIndicador = new javax.swing.JLabel();
        jTextFieldBuscador = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jPanelComidaEncontrada = new javax.swing.JPanel();
        jLabelMostrarCodigo = new javax.swing.JLabel();
        jLabelMostrarNombre = new javax.swing.JLabel();
        jLabelMostrarTipoComida = new javax.swing.JLabel();
        jLabelMostrarCantidadIngredientes = new javax.swing.JLabel();
        jLabelMostrarValor = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldCantidadIngredientes = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jPanelSuperior1 = new javax.swing.JPanel();
        jLabelTituloJFrame1 = new javax.swing.JLabel();
        jLabelIconoOrganizacion1 = new javax.swing.JLabel();
        jPanelCentral1 = new javax.swing.JPanel();
        jPanelComidaNoEncontrada1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelIndicador1 = new javax.swing.JLabel();
        jTextFieldBuscador1 = new javax.swing.JTextField();
        jButtonBuscar1 = new javax.swing.JButton();
        jPanelComidaEncontrada1 = new javax.swing.JPanel();
        jLabelMostrarCodigo1 = new javax.swing.JLabel();
        jLabelMostrarNombre1 = new javax.swing.JLabel();
        jLabelMostrarTipoComida1 = new javax.swing.JLabel();
        jLabelMostrarCantidadIngredientes1 = new javax.swing.JLabel();
        jLabelMostrarValor1 = new javax.swing.JLabel();
        jTextFieldCodigo1 = new javax.swing.JTextField();
        jTextFieldCantidadIngredientes1 = new javax.swing.JTextField();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jTextFieldTipo1 = new javax.swing.JTextField();
        jTextFieldValor1 = new javax.swing.JTextField();
        jPanelInferior1 = new javax.swing.JPanel();

        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);

        jPanelInferior.setBackground(new java.awt.Color(102, 102, 102));
        jPanelInferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153)));

        javax.swing.GroupLayout jPanelInferiorLayout = new javax.swing.GroupLayout(jPanelInferior);
        jPanelInferior.setLayout(jPanelInferiorLayout);
        jPanelInferiorLayout.setHorizontalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelInferiorLayout.setVerticalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanelInferior, java.awt.BorderLayout.PAGE_END);

        jPanelSuperior.setBackground(new java.awt.Color(204, 255, 255));
        jPanelSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));

        jLabelTituloJFrame.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloJFrame.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTituloJFrame.setText("CONSULTAR COMIDA");

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabelIconoOrganizacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTituloJFrame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloJFrame)
                    .addComponent(jLabelIconoOrganizacion))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jInternalFrame1.getContentPane().add(jPanelSuperior, java.awt.BorderLayout.PAGE_START);

        jPanelCentral.setBackground(new java.awt.Color(102, 102, 102));
        jPanelCentral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));

        jPanelComidaNoEncontrada.setBackground(new java.awt.Color(255, 204, 204));
        jPanelComidaNoEncontrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("COMIDA NO ENCONTRADA");

        javax.swing.GroupLayout jPanelComidaNoEncontradaLayout = new javax.swing.GroupLayout(jPanelComidaNoEncontrada);
        jPanelComidaNoEncontrada.setLayout(jPanelComidaNoEncontradaLayout);
        jPanelComidaNoEncontradaLayout.setHorizontalGroup(
            jPanelComidaNoEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaNoEncontradaLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel1)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanelComidaNoEncontradaLayout.setVerticalGroup(
            jPanelComidaNoEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaNoEncontradaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabelIndicador.setBackground(new java.awt.Color(0, 0, 0));
        jLabelIndicador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelIndicador.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIndicador.setText("Digita el Código de la Comida:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jPanelComidaEncontrada.setBackground(new java.awt.Color(204, 255, 255));
        jPanelComidaEncontrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));

        jLabelMostrarCodigo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMostrarCodigo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMostrarCodigo.setText("Codigo:");

        jLabelMostrarNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMostrarNombre.setText("Nombre:");

        jLabelMostrarTipoComida.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMostrarTipoComida.setText("Tipo de Comida:");

        jLabelMostrarCantidadIngredientes.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMostrarCantidadIngredientes.setText("Cantidad de Ingredientes:");

        jLabelMostrarValor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMostrarValor.setText("Valor :");

        jTextFieldCodigo.setText(" ");
        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });

        jTextFieldNombre.setText("                 ");

        jTextFieldTipo.setText(" ");
        jTextFieldTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelComidaEncontradaLayout = new javax.swing.GroupLayout(jPanelComidaEncontrada);
        jPanelComidaEncontrada.setLayout(jPanelComidaEncontradaLayout);
        jPanelComidaEncontradaLayout.setHorizontalGroup(
            jPanelComidaEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaEncontradaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelComidaEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMostrarCodigo)
                    .addGroup(jPanelComidaEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelMostrarTipoComida)
                        .addComponent(jLabelMostrarNombre, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabelMostrarCantidadIngredientes)
                    .addComponent(jLabelMostrarValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelComidaEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jTextFieldTipo)
                    .addComponent(jTextFieldCantidadIngredientes)
                    .addComponent(jTextFieldCodigo)
                    .addComponent(jTextFieldValor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelComidaEncontradaLayout.setVerticalGroup(
            jPanelComidaEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaEncontradaLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanelComidaEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelComidaEncontradaLayout.createSequentialGroup()
                        .addGroup(jPanelComidaEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelComidaEncontradaLayout.createSequentialGroup()
                                .addGroup(jPanelComidaEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMostrarCodigo)
                                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelMostrarNombre))
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelComidaEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMostrarTipoComida)
                            .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMostrarCantidadIngredientes))
                    .addComponent(jTextFieldCantidadIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelComidaEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMostrarValor)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(jLabelIndicador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar)
                .addGap(29, 29, 29))
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelComidaNoEncontrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelComidaEncontrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIndicador)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelComidaEncontrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelComidaNoEncontrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jInternalFrame1.getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(jInternalFrame1, java.awt.BorderLayout.CENTER);

        jPanelSuperior1.setBackground(new java.awt.Color(204, 255, 255));
        jPanelSuperior1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));

        jLabelTituloJFrame1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloJFrame1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTituloJFrame1.setText("CONSULTAR COMIDA");

        javax.swing.GroupLayout jPanelSuperior1Layout = new javax.swing.GroupLayout(jPanelSuperior1);
        jPanelSuperior1.setLayout(jPanelSuperior1Layout);
        jPanelSuperior1Layout.setHorizontalGroup(
            jPanelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperior1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabelIconoOrganizacion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                .addComponent(jLabelTituloJFrame1)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        jPanelSuperior1Layout.setVerticalGroup(
            jPanelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperior1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloJFrame1)
                    .addComponent(jLabelIconoOrganizacion1))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelSuperior1, java.awt.BorderLayout.PAGE_START);

        jPanelCentral1.setBackground(new java.awt.Color(102, 102, 102));
        jPanelCentral1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));

        jPanelComidaNoEncontrada1.setBackground(new java.awt.Color(255, 204, 204));
        jPanelComidaNoEncontrada1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 102));
        jLabel2.setText("COMIDA NO ENCONTRADA");

        javax.swing.GroupLayout jPanelComidaNoEncontrada1Layout = new javax.swing.GroupLayout(jPanelComidaNoEncontrada1);
        jPanelComidaNoEncontrada1.setLayout(jPanelComidaNoEncontrada1Layout);
        jPanelComidaNoEncontrada1Layout.setHorizontalGroup(
            jPanelComidaNoEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaNoEncontrada1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel2)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanelComidaNoEncontrada1Layout.setVerticalGroup(
            jPanelComidaNoEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaNoEncontrada1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabelIndicador1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelIndicador1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelIndicador1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIndicador1.setText("Digita el Código de la Comida:");

        jButtonBuscar1.setText("Buscar");
        jButtonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscar1ActionPerformed(evt);
            }
        });

        jPanelComidaEncontrada1.setBackground(new java.awt.Color(204, 255, 255));
        jPanelComidaEncontrada1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));

        jLabelMostrarCodigo1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMostrarCodigo1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMostrarCodigo1.setText("Codigo:");

        jLabelMostrarNombre1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMostrarNombre1.setText("Nombre:");

        jLabelMostrarTipoComida1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMostrarTipoComida1.setText("Tipo de Comida:");

        jLabelMostrarCantidadIngredientes1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMostrarCantidadIngredientes1.setText("Cantidad de Ingredientes:");

        jLabelMostrarValor1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMostrarValor1.setText("Valor :");

        jTextFieldCodigo1.setText(" ");
        jTextFieldCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigo1ActionPerformed(evt);
            }
        });

        jTextFieldNombre1.setText("                 ");

        jTextFieldTipo1.setText(" ");
        jTextFieldTipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelComidaEncontrada1Layout = new javax.swing.GroupLayout(jPanelComidaEncontrada1);
        jPanelComidaEncontrada1.setLayout(jPanelComidaEncontrada1Layout);
        jPanelComidaEncontrada1Layout.setHorizontalGroup(
            jPanelComidaEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaEncontrada1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelComidaEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMostrarCodigo1)
                    .addGroup(jPanelComidaEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelMostrarTipoComida1)
                        .addComponent(jLabelMostrarNombre1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabelMostrarCantidadIngredientes1)
                    .addComponent(jLabelMostrarValor1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelComidaEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNombre1)
                    .addComponent(jTextFieldTipo1)
                    .addComponent(jTextFieldCantidadIngredientes1)
                    .addComponent(jTextFieldCodigo1)
                    .addComponent(jTextFieldValor1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelComidaEncontrada1Layout.setVerticalGroup(
            jPanelComidaEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaEncontrada1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanelComidaEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelComidaEncontrada1Layout.createSequentialGroup()
                        .addGroup(jPanelComidaEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelComidaEncontrada1Layout.createSequentialGroup()
                                .addGroup(jPanelComidaEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMostrarCodigo1)
                                    .addComponent(jTextFieldCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelMostrarNombre1))
                            .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelComidaEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMostrarTipoComida1)
                            .addComponent(jTextFieldTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMostrarCantidadIngredientes1))
                    .addComponent(jTextFieldCantidadIngredientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelComidaEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMostrarValor1)
                    .addComponent(jTextFieldValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanelInferior1.setBackground(new java.awt.Color(102, 102, 102));
        jPanelInferior1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153)));

        javax.swing.GroupLayout jPanelInferior1Layout = new javax.swing.GroupLayout(jPanelInferior1);
        jPanelInferior1.setLayout(jPanelInferior1Layout);
        jPanelInferior1Layout.setHorizontalGroup(
            jPanelInferior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1042, Short.MAX_VALUE)
        );
        jPanelInferior1Layout.setVerticalGroup(
            jPanelInferior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCentral1Layout = new javax.swing.GroupLayout(jPanelCentral1);
        jPanelCentral1.setLayout(jPanelCentral1Layout);
        jPanelCentral1Layout.setHorizontalGroup(
            jPanelCentral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentral1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelIndicador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBuscador1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar1)
                .addGap(29, 29, 29))
            .addGroup(jPanelCentral1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCentral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelComidaNoEncontrada1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelComidaEncontrada1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCentral1Layout.createSequentialGroup()
                .addComponent(jPanelInferior1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCentral1Layout.setVerticalGroup(
            jPanelCentral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentral1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelCentral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIndicador1)
                    .addComponent(jButtonBuscar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelComidaEncontrada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelComidaNoEncontrada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInferior1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanelCentral1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

        String codigoBuscado = jTextFieldBuscador.getText();
        
        LinkedList<Comida> lista = this.objRestaurante.getListaComidas();
        boolean comidaEncontrada = false;

        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).getCodigo()==(codigoBuscado)) {
                Comida objComida=lista.get(i);
                jTextFieldCodigo.setText(objComida.getCodigo());
                jTextFieldCodigo.setEditable(false);
                jTextFieldNombre.setText(objComida.getNombre());
                jTextFieldNombre.setEditable(false);
                jTextFieldTipo.setText(objComida.getTipoComida());
                jTextFieldTipo.setEditable(false);
                jTextFieldCantidadIngredientes.setText(String.valueOf(objComida.getCantidadIngredientes()));
                jTextFieldCantidadIngredientes.setEditable(false);
                jTextFieldValor.setText(String.valueOf(objComida.getValor()));
                jTextFieldValor.setEditable(false);
                comidaEncontrada = true;

                this.jPanelComidaNoEncontrada.setVisible(false);
                this.jPanelComidaEncontrada.setVisible(true);

                break;
            }
        }

        if (!comidaEncontrada) {

            this.jPanelComidaEncontrada.setVisible(false);
            this.jPanelComidaNoEncontrada.setVisible(true);
        }

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jTextFieldTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoActionPerformed

    private void jButtonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscar1ActionPerformed

        String codigoBuscado = jTextFieldBuscador.getText();

        LinkedList<Comida> lista = this.objRestaurante.getListaComidas();
        boolean comidaEncontrada = false;

        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).getCodigo().equals(codigoBuscado)) {
                Comida objComida=lista.get(i);
                jTextFieldCodigo.setText(objComida.getCodigo());
                jTextFieldCodigo.setEditable(false);
                jTextFieldNombre.setText(objComida.getNombre());
                jTextFieldNombre.setEditable(false);
                jTextFieldTipo.setText(objComida.getTipoComida());
                jTextFieldTipo.setEditable(false);
                jTextFieldCantidadIngredientes.setText(String.valueOf(objComida.getCantidadIngredientes()));
                jTextFieldCantidadIngredientes.setEditable(false);
                jTextFieldValor.setText(String.valueOf(objComida.getValor()));
                jTextFieldValor.setEditable(false);
                comidaEncontrada = true;

                this.jPanelComidaNoEncontrada.setVisible(false);
                this.jPanelComidaEncontrada.setVisible(true);

                break;
            }
        }

        if (!comidaEncontrada) {

            this.jPanelComidaEncontrada.setVisible(false);
            this.jPanelComidaNoEncontrada.setVisible(true);
        }

    }//GEN-LAST:event_jButtonBuscar1ActionPerformed

    private void jTextFieldCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigo1ActionPerformed

    private void jTextFieldTipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonBuscar1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelIconoOrganizacion;
    private javax.swing.JLabel jLabelIconoOrganizacion1;
    private javax.swing.JLabel jLabelIndicador;
    private javax.swing.JLabel jLabelIndicador1;
    private javax.swing.JLabel jLabelMostrarCantidadIngredientes;
    private javax.swing.JLabel jLabelMostrarCantidadIngredientes1;
    private javax.swing.JLabel jLabelMostrarCodigo;
    private javax.swing.JLabel jLabelMostrarCodigo1;
    private javax.swing.JLabel jLabelMostrarNombre;
    private javax.swing.JLabel jLabelMostrarNombre1;
    private javax.swing.JLabel jLabelMostrarTipoComida;
    private javax.swing.JLabel jLabelMostrarTipoComida1;
    private javax.swing.JLabel jLabelMostrarValor;
    private javax.swing.JLabel jLabelMostrarValor1;
    private javax.swing.JLabel jLabelTituloJFrame;
    private javax.swing.JLabel jLabelTituloJFrame1;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelCentral1;
    private javax.swing.JPanel jPanelComidaEncontrada;
    private javax.swing.JPanel jPanelComidaEncontrada1;
    private javax.swing.JPanel jPanelComidaNoEncontrada;
    private javax.swing.JPanel jPanelComidaNoEncontrada1;
    private javax.swing.JPanel jPanelInferior;
    private javax.swing.JPanel jPanelInferior1;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JPanel jPanelSuperior1;
    private javax.swing.JTextField jTextFieldBuscador;
    private javax.swing.JTextField jTextFieldBuscador1;
    private javax.swing.JTextField jTextFieldCantidadIngredientes;
    private javax.swing.JTextField jTextFieldCantidadIngredientes1;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCodigo1;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldTipo;
    private javax.swing.JTextField jTextFieldTipo1;
    private javax.swing.JTextField jTextFieldValor;
    private javax.swing.JTextField jTextFieldValor1;
    // End of variables declaration//GEN-END:variables
}
