
package vista1;

/**
 *
 * @author munoz
 */
public class VtnGestionarComidas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VtnGestionarComidas
     */
    public VtnGestionarComidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanelSuperior = new javax.swing.JPanel();
        jLabelTituloJInternalFrame = new javax.swing.JLabel();
        jLabelIconoOrganizacion = new javax.swing.JLabel();
        jPanelInferior = new javax.swing.JPanel();
        jPanelCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMostrarComidas = new javax.swing.JTable();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonAtualizarLista = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanelSuperior1 = new javax.swing.JPanel();
        jLabelTituloJInternalFrame1 = new javax.swing.JLabel();
        jLabelIconoOrganizacion1 = new javax.swing.JLabel();
        jPanelInferior1 = new javax.swing.JPanel();
        jPanelCentral1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMostrarComidas1 = new javax.swing.JTable();
        jButtonRegistrar1 = new javax.swing.JButton();
        jButtonAtualizarLista1 = new javax.swing.JButton();

        jInternalFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);

        jPanelSuperior.setBackground(new java.awt.Color(204, 255, 255));
        jPanelSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153)));

        jLabelTituloJInternalFrame.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTituloJInternalFrame.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloJInternalFrame.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTituloJInternalFrame.setText("GESTIONAR COMIDAS");

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabelIconoOrganizacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTituloJInternalFrame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIconoOrganizacion)
                    .addComponent(jLabelTituloJInternalFrame))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jInternalFrame1.getContentPane().add(jPanelSuperior, java.awt.BorderLayout.PAGE_START);

        jPanelInferior.setBackground(new java.awt.Color(102, 102, 102));
        jPanelInferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153)));

        javax.swing.GroupLayout jPanelInferiorLayout = new javax.swing.GroupLayout(jPanelInferior);
        jPanelInferior.setLayout(jPanelInferiorLayout);
        jPanelInferiorLayout.setHorizontalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelInferiorLayout.setVerticalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanelInferior, java.awt.BorderLayout.PAGE_END);

        jPanelCentral.setBackground(new java.awt.Color(102, 102, 102));
        jPanelCentral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153)));

        jTableMostrarComidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMostrarComidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMostrarComidasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMostrarComidas);

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonAtualizarLista.setText("Actualizar Listado");
        jButtonAtualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addComponent(jButtonAtualizarLista)
                        .addGap(245, 245, 245)
                        .addComponent(jButtonRegistrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAtualizarLista)
                    .addComponent(jButtonRegistrar))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFrame1.getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(jInternalFrame1, java.awt.BorderLayout.CENTER);

        jInternalFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jInternalFrame2.setIconifiable(true);
        jInternalFrame2.setMaximizable(true);
        jInternalFrame2.setResizable(true);

        jPanelSuperior1.setBackground(new java.awt.Color(204, 255, 255));
        jPanelSuperior1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153)));

        jLabelTituloJInternalFrame1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTituloJInternalFrame1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloJInternalFrame1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTituloJInternalFrame1.setText("GESTIONAR COMIDAS");

        javax.swing.GroupLayout jPanelSuperior1Layout = new javax.swing.GroupLayout(jPanelSuperior1);
        jPanelSuperior1.setLayout(jPanelSuperior1Layout);
        jPanelSuperior1Layout.setHorizontalGroup(
            jPanelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperior1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabelIconoOrganizacion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTituloJInternalFrame1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSuperior1Layout.setVerticalGroup(
            jPanelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperior1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIconoOrganizacion1)
                    .addComponent(jLabelTituloJInternalFrame1))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jInternalFrame2.getContentPane().add(jPanelSuperior1, java.awt.BorderLayout.PAGE_START);

        jPanelInferior1.setBackground(new java.awt.Color(102, 102, 102));
        jPanelInferior1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153)));

        javax.swing.GroupLayout jPanelInferior1Layout = new javax.swing.GroupLayout(jPanelInferior1);
        jPanelInferior1.setLayout(jPanelInferior1Layout);
        jPanelInferior1Layout.setHorizontalGroup(
            jPanelInferior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelInferior1Layout.setVerticalGroup(
            jPanelInferior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame2.getContentPane().add(jPanelInferior1, java.awt.BorderLayout.PAGE_END);

        jPanelCentral1.setBackground(new java.awt.Color(102, 102, 102));
        jPanelCentral1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153)));

        jTableMostrarComidas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMostrarComidas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMostrarComidas1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableMostrarComidas1);

        jButtonRegistrar1.setText("Registrar");
        jButtonRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrar1ActionPerformed(evt);
            }
        });

        jButtonAtualizarLista1.setText("Actualizar Listado");
        jButtonAtualizarLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarLista1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCentral1Layout = new javax.swing.GroupLayout(jPanelCentral1);
        jPanelCentral1.setLayout(jPanelCentral1Layout);
        jPanelCentral1Layout.setHorizontalGroup(
            jPanelCentral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentral1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCentral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentral1Layout.createSequentialGroup()
                        .addComponent(jButtonAtualizarLista1)
                        .addGap(245, 245, 245)
                        .addComponent(jButtonRegistrar1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCentral1Layout.setVerticalGroup(
            jPanelCentral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentral1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCentral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAtualizarLista1)
                    .addComponent(jButtonRegistrar1))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFrame2.getContentPane().add(jPanelCentral1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jInternalFrame2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMostrarComidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMostrarComidasMouseClicked
        int column = this.jTableMostrarComidas.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/jTableMostrarComidas.getRowHeight();
        if(row < jTableMostrarComidas.getRowCount() && row >= 0 && column < jTableMostrarComidas.getColumnCount() && column >= 0){
            Object value = jTableMostrarComidas.getValueAt(row, column);

            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;

                String idComida = jTableMostrarComidas.getValueAt(row, 0).toString();
                if(boton.getName().equals("Eliminar")){
                    this.elimininarComida(idComida);
                }
            }
        }
    }//GEN-LAST:event_jTableMostrarComidasMouseClicked

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        RegistrarComida vtnObjRegistrarcomida= new RegistrarComida(objRestaurante);
        vtnObjRegistrarcomida.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        vtnObjRegistrarcomida.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonAtualizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarListaActionPerformed

        llenarTabla();
        System.out.println("dsds");
    }//GEN-LAST:event_jButtonAtualizarListaActionPerformed

    private void jTableMostrarComidas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMostrarComidas1MouseClicked
        int column = this.jTableMostrarComidas.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/jTableMostrarComidas.getRowHeight();
        if(row < jTableMostrarComidas.getRowCount() && row >= 0 && column < jTableMostrarComidas.getColumnCount() && column >= 0){
            Object value = jTableMostrarComidas.getValueAt(row, column);

            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;

                String idComida = jTableMostrarComidas.getValueAt(row, 0).toString();
                if(boton.getName().equals("Eliminar")){
                    this.elimininarComida(idComida);
                }
            }
        }
    }//GEN-LAST:event_jTableMostrarComidas1MouseClicked

    private void jButtonRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrar1ActionPerformed
        RegistrarComida vtnObjRegistrarcomida= new RegistrarComida(objRestaurante);
        vtnObjRegistrarcomida.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        vtnObjRegistrarcomida.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrar1ActionPerformed

    private void jButtonAtualizarLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarLista1ActionPerformed

        llenarTabla();
        System.out.println("dsds");
    }//GEN-LAST:event_jButtonAtualizarLista1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarLista;
    private javax.swing.JButton jButtonAtualizarLista1;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonRegistrar1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabelIconoOrganizacion;
    private javax.swing.JLabel jLabelIconoOrganizacion1;
    private javax.swing.JLabel jLabelTituloJInternalFrame;
    private javax.swing.JLabel jLabelTituloJInternalFrame1;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelCentral1;
    private javax.swing.JPanel jPanelInferior;
    private javax.swing.JPanel jPanelInferior1;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JPanel jPanelSuperior1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMostrarComidas;
    private javax.swing.JTable jTableMostrarComidas1;
    // End of variables declaration//GEN-END:variables
}
