package vista;

import java.util.Date;
import modelos.Comida;
import servicios.ComidaServices;
import utilidades.Utilidades;

/**
 *
 * @author LENOVO
 */
public class vtnActualizarComida extends javax.swing.JFrame {

  private final ComidaServices objComidaServices;
  private Integer idComidaActual;
  private String correoAnterior;

  public vtnActualizarComida(ComidaServices objComidaServices) {
    initComponents();
    this.objComidaServices = objComidaServices;
  }

  public void actualizarFormularioComida(
    Integer idComidaActual,
    Comida objComida
  ) {
    this.idComidaActual = idComidaActual;
    this.jTextFieldIdComida.setText(objComida.getIdComida() + "");
    this.jTextFieldNombre.setText(objComida.getNombre());
    // this.jTextFieldApellidos.setText(objComida.getApellido());
    // this.jTextFieldCorreo.setText(objComida.getEmail());
    // this.correoAnterior = objComida.getEmail();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jPanelInferior = new javax.swing.JPanel();
    jLabelDesarrolladoPor = new javax.swing.JLabel();
    jPanelSuperior = new javax.swing.JPanel();
    jLabelTituloJForm = new javax.swing.JLabel();
    jPanelCentral = new javax.swing.JPanel();
    jLabelNombres = new javax.swing.JLabel();
    jLabelCorreo = new javax.swing.JLabel();
    jTextFieldNombre = new javax.swing.JTextField();
    jLabelApellidos = new javax.swing.JLabel();
    jTextFieldCodigo = new javax.swing.JTextField();
    jButtonActualizar = new javax.swing.JButton();
    jTextFieldRestaurante = new javax.swing.JTextField();
    jLabelIdComida = new javax.swing.JLabel();
    jTextFieldIdComida = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanelInferior.setBorder(
      javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))
    );

    jLabelDesarrolladoPor.setText("Desarrollado por inform�tica III");

    javax.swing.GroupLayout jPanelInferiorLayout = new javax.swing.GroupLayout(
      jPanelInferior
    );
    jPanelInferior.setLayout(jPanelInferiorLayout);
    jPanelInferiorLayout.setHorizontalGroup(
      jPanelInferiorLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanelInferiorLayout
            .createSequentialGroup()
            .addGap(194, 194, 194)
            .addComponent(jLabelDesarrolladoPor)
            .addContainerGap(196, Short.MAX_VALUE)
        )
    );
    jPanelInferiorLayout.setVerticalGroup(
      jPanelInferiorLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          jPanelInferiorLayout
            .createSequentialGroup()
            .addContainerGap(48, Short.MAX_VALUE)
            .addComponent(jLabelDesarrolladoPor)
            .addGap(38, 38, 38)
        )
    );

    getContentPane().add(jPanelInferior, java.awt.BorderLayout.PAGE_END);

    jPanelSuperior.setBorder(
      javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))
    );

    jLabelTituloJForm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabelTituloJForm.setForeground(new java.awt.Color(0, 51, 153));
    jLabelTituloJForm.setText("Actualizar cliente");

    javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(
      jPanelSuperior
    );
    jPanelSuperior.setLayout(jPanelSuperiorLayout);
    jPanelSuperiorLayout.setHorizontalGroup(
      jPanelSuperiorLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          jPanelSuperiorLayout
            .createSequentialGroup()
            .addContainerGap(181, Short.MAX_VALUE)
            .addComponent(jLabelTituloJForm)
            .addGap(203, 203, 203)
        )
    );
    jPanelSuperiorLayout.setVerticalGroup(
      jPanelSuperiorLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanelSuperiorLayout
            .createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jLabelTituloJForm)
            .addContainerGap(59, Short.MAX_VALUE)
        )
    );

    getContentPane().add(jPanelSuperior, java.awt.BorderLayout.PAGE_START);

    jPanelCentral.setBorder(
      javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))
    );
    jPanelCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabelNombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabelNombres.setForeground(new java.awt.Color(0, 0, 102));
    jLabelNombres.setText("Nombres:");
    jPanelCentral.add(
      jLabelNombres,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1)
    );

    jLabelCorreo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabelCorreo.setForeground(new java.awt.Color(0, 0, 102));
    jLabelCorreo.setText("Correo:");
    jPanelCentral.add(
      jLabelCorreo,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1)
    );
    jPanelCentral.add(
      jTextFieldNombre,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 130, -1)
    );

    jLabelApellidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabelApellidos.setForeground(new java.awt.Color(0, 0, 102));
    jLabelApellidos.setText("Apellidos:");
    jPanelCentral.add(
      jLabelApellidos,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1)
    );
    jPanelCentral.add(
      jTextFieldCodigo,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 130, -1)
    );

    jButtonActualizar.setIcon(
      new javax.swing.ImageIcon(getClass().getResource("/recursos/grabar.png"))
    ); // NOI18N
    jButtonActualizar.setText("Actualizar");
    jButtonActualizar.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButtonActualizarActionPerformed(evt);
        }
      }
    );
    jPanelCentral.add(
      jButtonActualizar,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1)
    );
    jPanelCentral.add(
      jTextFieldRestaurante,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 130, -1)
    );

    jLabelIdComida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabelIdComida.setForeground(new java.awt.Color(0, 0, 102));
    jLabelIdComida.setText("Id Comida:");
    jPanelCentral.add(
      jLabelIdComida,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1)
    );

    jTextFieldIdComida.setEditable(false);
    jPanelCentral.add(
      jTextFieldIdComida,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 130, -1)
    );

    getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jButtonActualizarActionPerformed(
    java.awt.event.ActionEvent evt
  ) { //GEN-FIRST:event_jButtonActualizarActionPerformed
    String nombre, codigo, restaurante, tipoComida;
    Integer idComida, cantidadIngredientes;
    Float precio = 0.0f;

    // Se capturan los datos desde los campos de texto del formulario

    // NOTA: Generar jTextFields para los campos faltantes (Corregir)
    String idComidaTmp = jTextFieldIdComida.getText();
    idComida = Integer.parseInt(idComidaTmp);
    String cantidadIngredientesTmp = jTextFieldIdComida.getText();
    cantidadIngredientes = Integer.parseInt(cantidadIngredientesTmp);
    nombre = jTextFieldNombre.getText();
    codigo = jTextFieldCodigo.getText();
    restaurante = jTextFieldRestaurante.getText();
    tipoComida = jTextFieldRestaurante.getText();

    Comida objComida = new Comida(
      idComida,
      restaurante,
      codigo,
      nombre,
      tipoComida,
      cantidadIngredientes,
      precio
    );

    if (
      !this.correoAnterior.equals(restaurante) &&
      this.objComidaServices.consultarSiExisteComidaPorCorreo(restaurante)
    ) {
      Utilidades.mensajeError(
        "Error, el correo del cliente se encuentra registrado",
        "Error al registrar el cliente"
      );
    } else {
      Comida objComidaCreado =
        this.objComidaServices.actualizarComida(objComida, this.idComidaActual);
      Utilidades.mensajeExito(
        "Comida actualizado exitosmente",
        "Comida actualizado"
      );
    }
  } //GEN-LAST:event_jButtonActualizarActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonActualizar;
  private javax.swing.JLabel jLabelApellidos;
  private javax.swing.JLabel jLabelCorreo;
  private javax.swing.JLabel jLabelDesarrolladoPor;
  private javax.swing.JLabel jLabelIdComida;
  private javax.swing.JLabel jLabelNombres;
  private javax.swing.JLabel jLabelTituloJForm;
  private javax.swing.JPanel jPanelCentral;
  private javax.swing.JPanel jPanelInferior;
  private javax.swing.JPanel jPanelSuperior;
  private javax.swing.JTextField jTextFieldCodigo;
  private javax.swing.JTextField jTextFieldRestaurante;
  private javax.swing.JTextField jTextFieldIdComida;
  private javax.swing.JTextField jTextFieldNombre;
  // End of variables declaration//GEN-END:variables
}
